//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPCodeGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KPCodeGenResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KPCodeGenResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KPCodeGen.Properties.KPCodeGenResource", typeof(KPCodeGenResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string KP_Description {
            get {
                return ResourceManager.GetString("KP_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor, selecione uma tabela para gerar o código fonte..
        /// </summary>
        internal static string KP_PleaseSelectTable {
            get {
                return ResourceManager.GetString("KP_PleaseSelectTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI.
        /// </summary>
        internal static string KPControl_AI {
            get {
                return ResourceManager.GetString("KPControl_AI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permite Nulo.
        /// </summary>
        internal static string KPControl_AllowNull {
            get {
                return ResourceManager.GetString("KPControl_AllowNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name:.
        /// </summary>
        internal static string KPControl_AssemblyName {
            get {
                return ResourceManager.GetString("KPControl_AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-Incremento.
        /// </summary>
        internal static string KPControl_AutoIncrement {
            get {
                return ResourceManager.GetString("KPControl_AutoIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração básica.
        /// </summary>
        internal static string KPControl_BasicSettings {
            get {
                return ResourceManager.GetString("KPControl_BasicSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coluna.
        /// </summary>
        internal static string KPControl_Column {
            get {
                return ResourceManager.GetString("KPControl_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente Form.
        /// </summary>
        internal static string KPControl_ComponentForm {
            get {
                return ResourceManager.GetString("KPControl_ComponentForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Componente View.
        /// </summary>
        internal static string KPControl_ComponentView {
            get {
                return ResourceManager.GetString("KPControl_ComponentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constraint.
        /// </summary>
        internal static string KPControl_Constraint {
            get {
                return ResourceManager.GetString("KPControl_Constraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo C#.
        /// </summary>
        internal static string KPControl_CSharpType {
            get {
                return ResourceManager.GetString("KPControl_CSharpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataLength.
        /// </summary>
        internal static string KPControl_DataLength {
            get {
                return ResourceManager.GetString("KPControl_DataLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owner do banco de dados.
        /// </summary>
        internal static string KPControl_DBOwner {
            get {
                return ResourceManager.GetString("KPControl_DBOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string KPControl_DisplayName {
            get {
                return ResourceManager.GetString("KPControl_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir. arquivo EntityBO:.
        /// </summary>
        internal static string KPControl_EntityBOFileDir {
            get {
                return ResourceManager.GetString("KPControl_EntityBOFileDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace (EntityBO):.
        /// </summary>
        internal static string KPControl_EntityBONamespace {
            get {
                return ResourceManager.GetString("KPControl_EntityBONamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir. arquivo Entity:.
        /// </summary>
        internal static string KPControl_EntityFileDir {
            get {
                return ResourceManager.GetString("KPControl_EntityFileDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entity Name:.
        /// </summary>
        internal static string KPControl_EntityName {
            get {
                return ResourceManager.GetString("KPControl_EntityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namespace (Entity):.
        /// </summary>
        internal static string KPControl_EntityNamespace {
            get {
                return ResourceManager.GetString("KPControl_EntityNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrar tabela....
        /// </summary>
        internal static string KPControl_FilterTable {
            get {
                return ResourceManager.GetString("KPControl_FilterTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coluna FK.
        /// </summary>
        internal static string KPControl_FKColumn {
            get {
                return ResourceManager.GetString("KPControl_FKColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela FK.
        /// </summary>
        internal static string KPControl_FKTable {
            get {
                return ResourceManager.GetString("KPControl_FKTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave Estrangeira.
        /// </summary>
        internal static string KPControl_ForeingKey {
            get {
                return ResourceManager.GetString("KPControl_ForeingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dir Arquivos Forms:.
        /// </summary>
        internal static string KPControl_FormFilesDir {
            get {
                return ResourceManager.GetString("KPControl_FormFilesDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Gerar.
        /// </summary>
        internal static string KPControl_Generate {
            get {
                return ResourceManager.GetString("KPControl_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamanho.
        /// </summary>
        internal static string KPControl_Lenght {
            get {
                return ResourceManager.GetString("KPControl_Lenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MappedDataType.
        /// </summary>
        internal static string KPControl_MappedDataType {
            get {
                return ResourceManager.GetString("KPControl_MappedDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaskType.
        /// </summary>
        internal static string KPControl_MaskType {
            get {
                return ResourceManager.GetString("KPControl_MaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nulo.
        /// </summary>
        internal static string KPControl_Null {
            get {
                return ResourceManager.GetString("KPControl_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casas Inteiras.
        /// </summary>
        internal static string KPControl_NumericPrecision {
            get {
                return ResourceManager.GetString("KPControl_NumericPrecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Casas Decimais.
        /// </summary>
        internal static string KPControl_NumericScale {
            get {
                return ResourceManager.GetString("KPControl_NumericScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PK.
        /// </summary>
        internal static string KPControl_PK {
            get {
                return ResourceManager.GetString("KPControl_PK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave Primária.
        /// </summary>
        internal static string KPControl_PrimaryKey {
            get {
                return ResourceManager.GetString("KPControl_PrimaryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definição da tabela.
        /// </summary>
        internal static string KPControl_TableDefinition {
            get {
                return ResourceManager.GetString("KPControl_TableDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo.
        /// </summary>
        internal static string KPControl_Type {
            get {
                return ResourceManager.GetString("KPControl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UN.
        /// </summary>
        internal static string KPControl_UN {
            get {
                return ResourceManager.GetString("KPControl_UN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chave Única.
        /// </summary>
        internal static string KPControl_UniqueKey {
            get {
                return ResourceManager.GetString("KPControl_UniqueKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade.
        /// </summary>
        internal static string KPEntity_Category_Property {
            get {
                return ResourceManager.GetString("KPEntity_Category_Property", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom [Configuração].
        /// </summary>
        internal static string KPEntity_Category_ZoomConfig {
            get {
                return ResourceManager.GetString("KPEntity_Category_ZoomConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor [Falso].
        /// </summary>
        internal static string KPEntity_CustomFalse {
            get {
                return ResourceManager.GetString("KPEntity_CustomFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor customizado quando o campo receber valor [False] - Falso.
        /// </summary>
        internal static string KPEntity_CustomFalse_Description {
            get {
                return ResourceManager.GetString("KPEntity_CustomFalse_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor [Verdadeiro].
        /// </summary>
        internal static string KPEntity_CustomTrue {
            get {
                return ResourceManager.GetString("KPEntity_CustomTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor customizado quando o campo receber valor [True] - Verdadeiro.
        /// </summary>
        internal static string KPEntity_CustomTrue_Description {
            get {
                return ResourceManager.GetString("KPEntity_CustomTrue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largura da descrição.
        /// </summary>
        internal static string KPEntity_DescriptionWidth {
            get {
                return ResourceManager.GetString("KPEntity_DescriptionWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largura do controle para visualização da descrição da FK..
        /// </summary>
        internal static string KPEntity_DescriptionWidth_Description {
            get {
                return ResourceManager.GetString("KPEntity_DescriptionWidth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplaySearchField.
        /// </summary>
        internal static string KPEntity_DisplaySearchField {
            get {
                return ResourceManager.GetString("KPEntity_DisplaySearchField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DisplaySearchField_Description.
        /// </summary>
        internal static string KPEntity_DisplaySearchField_Description {
            get {
                return ResourceManager.GetString("KPEntity_DisplaySearchField_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eventos.
        /// </summary>
        internal static string KPEntity_Events {
            get {
                return ResourceManager.GetString("KPEntity_Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Prop. FK.
        /// </summary>
        internal static string KPEntity_FieldNameDescription {
            get {
                return ResourceManager.GetString("KPEntity_FieldNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da propridade da entidade FK, terá como objetivo retornar a descrição para o controle..
        /// </summary>
        internal static string KPEntity_FieldNameDescription_Description {
            get {
                return ResourceManager.GetString("KPEntity_FieldNameDescription_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade ID retorno.
        /// </summary>
        internal static string KPEntity_FieldReturnId {
            get {
                return ResourceManager.GetString("KPEntity_FieldReturnId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade que terá seu valor guardado na chave do Zoom..
        /// </summary>
        internal static string KPEntity_FieldReturnId_Description {
            get {
                return ResourceManager.GetString("KPEntity_FieldReturnId_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propridade texto.
        /// </summary>
        internal static string KPEntity_FieldReturnText {
            get {
                return ResourceManager.GetString("KPEntity_FieldReturnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade que terá seu valor visualizável no campo descrição do Zoom..
        /// </summary>
        internal static string KPEntity_FieldReturnText_Description {
            get {
                return ResourceManager.GetString("KPEntity_FieldReturnText_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título do campo na Grid. [HeaderName] representa a nomeação da coluna do grid. Caso não seja preenchida, automaticamente será incluído o valor que foi definido no título da propriedade na entidade..
        /// </summary>
        internal static string KPEntity_HeaderName_Description {
            get {
                return ResourceManager.GetString("KPEntity_HeaderName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura.
        /// </summary>
        internal static string KPEntity_Height {
            get {
                return ResourceManager.GetString("KPEntity_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determina a altura do controle..
        /// </summary>
        internal static string KPEntity_Height_Description {
            get {
                return ResourceManager.GetString("KPEntity_Height_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura tela Zoom.
        /// </summary>
        internal static string KPEntity_HeightZoom {
            get {
                return ResourceManager.GetString("KPEntity_HeightZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura da tela do Zoom..
        /// </summary>
        internal static string KPEntity_HeightZoom_Description {
            get {
                return ResourceManager.GetString("KPEntity_HeightZoom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-linha.
        /// </summary>
        internal static string KPEntity_IsMultiline {
            get {
                return ResourceManager.GetString("KPEntity_IsMultiline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Define que a caixa de texto terá mais de uma linha..
        /// </summary>
        internal static string KPEntity_IsMultiline_Description {
            get {
                return ResourceManager.GetString("KPEntity_IsMultiline_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório.
        /// </summary>
        internal static string KPEntity_IsRequired {
            get {
                return ResourceManager.GetString("KPEntity_IsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adiciona um &quot;*&quot; no controle evidenciando que ele é obrigatório..
        /// </summary>
        internal static string KPEntity_IsRequired_Description {
            get {
                return ResourceManager.GetString("KPEntity_IsRequired_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordenável.
        /// </summary>
        internal static string KPEntity_IsSortable {
            get {
                return ResourceManager.GetString("KPEntity_IsSortable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determina se a coluna no grid aceita ordenação..
        /// </summary>
        internal static string KPEntity_IsSortable_Description {
            get {
                return ResourceManager.GetString("KPEntity_IsSortable_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visível.
        /// </summary>
        internal static string KPEntity_IsVisible {
            get {
                return ResourceManager.GetString("KPEntity_IsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determina se a coluna do grid será visualizada..
        /// </summary>
        internal static string KPEntity_IsVisible_Description {
            get {
                return ResourceManager.GetString("KPEntity_IsVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento lançado quando o usuário deleta uma linha da grid. .
        /// </summary>
        internal static string KPEntity_KPEventDeleteLine_Description {
            get {
                return ResourceManager.GetString("KPEntity_KPEventDeleteLine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento lançado quando o controle perde o foco..
        /// </summary>
        internal static string KPEntity_KPEventTextLostFocus_Description {
            get {
                return ResourceManager.GetString("KPEntity_KPEventTextLostFocus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evento lançado quando o usuário sai do foco do controle..
        /// </summary>
        internal static string KPEntity_KPEventZoomLostFocus_Description {
            get {
                return ResourceManager.GetString("KPEntity_KPEventZoomLostFocus_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapeamento FK.
        /// </summary>
        internal static string KPEntity_Mapping_FK {
            get {
                return ResourceManager.GetString("KPEntity_Mapping_FK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Máscara.
        /// </summary>
        internal static string KPEntity_MaskType {
            get {
                return ResourceManager.GetString("KPEntity_MaskType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determina a máscara de caracteres que o controle irá obrigar..
        /// </summary>
        internal static string KPEntity_MaskType_Description {
            get {
                return ResourceManager.GetString("KPEntity_MaskType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade campo de busca.
        /// </summary>
        internal static string KPEntity_SearchByField {
            get {
                return ResourceManager.GetString("KPEntity_SearchByField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Propriedade que terá como alvo o campo que o Zoom fará as pesquisas..
        /// </summary>
        internal static string KPEntity_SearchByField_Description {
            get {
                return ResourceManager.GetString("KPEntity_SearchByField_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título.
        /// </summary>
        internal static string KPEntity_Title {
            get {
                return ResourceManager.GetString("KPEntity_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título do campo. O Título por padrão vem da entidade, porém é possível sobrescreve-lo na tela caso preencha este propriedade..
        /// </summary>
        internal static string KPEntity_Title_Description {
            get {
                return ResourceManager.GetString("KPEntity_Title_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título Zoom.
        /// </summary>
        internal static string KPEntity_Title_Zoom {
            get {
                return ResourceManager.GetString("KPEntity_Title_Zoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título da tela do Zoom ao abrir..
        /// </summary>
        internal static string KPEntity_Title_Zoom_Description {
            get {
                return ResourceManager.GetString("KPEntity_Title_Zoom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largura.
        /// </summary>
        internal static string KPEntity_Width {
            get {
                return ResourceManager.GetString("KPEntity_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determina a largura do controle..
        /// </summary>
        internal static string KPEntity_Width_Description {
            get {
                return ResourceManager.GetString("KPEntity_Width_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largura tela Zoom.
        /// </summary>
        internal static string KPEntity_WidthZoom {
            get {
                return ResourceManager.GetString("KPEntity_WidthZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Largura da tela do Zoom..
        /// </summary>
        internal static string KPEntity_WidthZoom_Description {
            get {
                return ResourceManager.GetString("KPEntity_WidthZoom_Description", resourceCulture);
            }
        }
    }
}
